#pragma once

#include "NativeGameplayTags.h"

namespace NPGamplayTags
{
	/** Input Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ItemListCall);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_NextSentence);

	/** Chapter Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chapter_Option_MainMenu);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chapter_00_Room);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chapter_00_Warehouse);
}