#pragma once

#include "NativeGameplayTags.h"

namespace NPGamplayTags
{
	/** Input Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ItemListCall);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_NextSentence);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PhoneCall);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HandLight);

	/** Chapter Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chapter_Option_MainMenu);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chapter_00_Room);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chapter_00_Warehouse);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chapter_00_MonitorRoom);

	/** Call Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Call_00_Tutorial);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Call_00_FindCart);

	/** Subscribes Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sub_00_Room);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sub_00_Room2);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sub_00_Start);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sub_00_GuideMet);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sub_00_GuideMet2);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sub_00_Video);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sub_00_Quest01);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sub_00_HandLight);

	/** States Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Call_Busy);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Call_Allow);

	/** Event Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Watched_TutorialVideo);

	/** Game Data Tags */
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_SaveGame_MetaData);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_SaveGame_Slot_1);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_SaveGame_Slot_2);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_SaveGame_Slot_3);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_SaveGame_Slot_4);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_SaveGame_Slot_5);
}