#pragma once

#include "NativeGameplayTags.h"

namespace NPGamplayTags
{
	// Input Tags
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	NAPOLITAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
}